/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TxSignatureRouteImport } from './routes/tx.$signature'
import { Route as TokenAddressRouteImport } from './routes/token.$address'
import { Route as ScamsAddressRouteImport } from './routes/scams.$address'
import { Route as DeveloperAddressRouteImport } from './routes/developer.$address'
import { Route as ClusterClusterIdRouteImport } from './routes/cluster.$clusterId'
import { Route as DeveloperDeveloperAddressTokenMintRouteImport } from './routes/developer.$developerAddress.token.$mint'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxSignatureRoute = TxSignatureRouteImport.update({
  id: '/tx/$signature',
  path: '/tx/$signature',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenAddressRoute = TokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamsAddressRoute = ScamsAddressRouteImport.update({
  id: '/scams/$address',
  path: '/scams/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperAddressRoute = DeveloperAddressRouteImport.update({
  id: '/developer/$address',
  path: '/developer/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusterClusterIdRoute = ClusterClusterIdRouteImport.update({
  id: '/cluster/$clusterId',
  path: '/cluster/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDeveloperAddressTokenMintRoute =
  DeveloperDeveloperAddressTokenMintRouteImport.update({
    id: '/developer/$developerAddress/token/$mint',
    path: '/developer/$developerAddress/token/$mint',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/cluster/$clusterId': typeof ClusterClusterIdRoute
  '/developer/$address': typeof DeveloperAddressRoute
  '/scams/$address': typeof ScamsAddressRoute
  '/token/$address': typeof TokenAddressRoute
  '/tx/$signature': typeof TxSignatureRoute
  '/developer/$developerAddress/token/$mint': typeof DeveloperDeveloperAddressTokenMintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/cluster/$clusterId': typeof ClusterClusterIdRoute
  '/developer/$address': typeof DeveloperAddressRoute
  '/scams/$address': typeof ScamsAddressRoute
  '/token/$address': typeof TokenAddressRoute
  '/tx/$signature': typeof TxSignatureRoute
  '/developer/$developerAddress/token/$mint': typeof DeveloperDeveloperAddressTokenMintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/cluster/$clusterId': typeof ClusterClusterIdRoute
  '/developer/$address': typeof DeveloperAddressRoute
  '/scams/$address': typeof ScamsAddressRoute
  '/token/$address': typeof TokenAddressRoute
  '/tx/$signature': typeof TxSignatureRoute
  '/developer/$developerAddress/token/$mint': typeof DeveloperDeveloperAddressTokenMintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/cluster/$clusterId'
    | '/developer/$address'
    | '/scams/$address'
    | '/token/$address'
    | '/tx/$signature'
    | '/developer/$developerAddress/token/$mint'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/cluster/$clusterId'
    | '/developer/$address'
    | '/scams/$address'
    | '/token/$address'
    | '/tx/$signature'
    | '/developer/$developerAddress/token/$mint'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/cluster/$clusterId'
    | '/developer/$address'
    | '/scams/$address'
    | '/token/$address'
    | '/tx/$signature'
    | '/developer/$developerAddress/token/$mint'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ClusterClusterIdRoute: typeof ClusterClusterIdRoute
  DeveloperAddressRoute: typeof DeveloperAddressRoute
  ScamsAddressRoute: typeof ScamsAddressRoute
  TokenAddressRoute: typeof TokenAddressRoute
  TxSignatureRoute: typeof TxSignatureRoute
  DeveloperDeveloperAddressTokenMintRoute: typeof DeveloperDeveloperAddressTokenMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/$signature': {
      id: '/tx/$signature'
      path: '/tx/$signature'
      fullPath: '/tx/$signature'
      preLoaderRoute: typeof TxSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$address': {
      id: '/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof TokenAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scams/$address': {
      id: '/scams/$address'
      path: '/scams/$address'
      fullPath: '/scams/$address'
      preLoaderRoute: typeof ScamsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/$address': {
      id: '/developer/$address'
      path: '/developer/$address'
      fullPath: '/developer/$address'
      preLoaderRoute: typeof DeveloperAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cluster/$clusterId': {
      id: '/cluster/$clusterId'
      path: '/cluster/$clusterId'
      fullPath: '/cluster/$clusterId'
      preLoaderRoute: typeof ClusterClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/$developerAddress/token/$mint': {
      id: '/developer/$developerAddress/token/$mint'
      path: '/developer/$developerAddress/token/$mint'
      fullPath: '/developer/$developerAddress/token/$mint'
      preLoaderRoute: typeof DeveloperDeveloperAddressTokenMintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ClusterClusterIdRoute: ClusterClusterIdRoute,
  DeveloperAddressRoute: DeveloperAddressRoute,
  ScamsAddressRoute: ScamsAddressRoute,
  TokenAddressRoute: TokenAddressRoute,
  TxSignatureRoute: TxSignatureRoute,
  DeveloperDeveloperAddressTokenMintRoute:
    DeveloperDeveloperAddressTokenMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
